services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 4000:4000
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${PWD}/initdb:/docker-entrypoint-initdb.d